<?php
return array(
  'default_group_description' => array(
    'group_name' => 'Relationship Group Sync Configuration',
    'group' => 'org.civicrm.relationshipgroupsync',
    'name' => 'default_group_description',
    'type' => 'String',
    'default' => ts('Relationship Group Sync: Automatic group of related contacts.'),
    'add' => '4.5',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Fields which are configured to use the slider widget',
    'help_text' => 'Default description for generated groups',
  ),
  'default_group_type' => array(
    'group_name' => 'Relationship Group Sync Configuration',
    'group' => 'org.civicrm.relationshipgroupsync',
    'name' => 'default_group_type',
    'type' => 'String',
    'default' => '',
    'add' => '4.5',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Default group type for generated groups',
    'help_text' => 'Default group type for generated groups',
  ),
  'smart_search_template' => array(
    'group_name' => 'Relationship Group Sync Configuration',
    'group' => 'org.civicrm.relationshipgroupsync',
    'name' => 'smart_search_template',
    'type' => 'String',
    'default' => $formValues = 'a:41:{s:12:"hidden_basic";s:1:"1";s:12:"contact_type";a:0:{}s:5:"group";a:0:{}s:10:"group_type";a:0:{}s:21:"group_search_selected";s:5:"group";s:12:"contact_tags";a:0:{}s:9:"sort_name";s:0:"";s:5:"email";s:0:"";s:14:"contact_source";s:0:"";s:9:"job_title";s:0:"";s:10:"contact_id";s:1:"0";s:19:"external_identifier";s:0:"";s:7:"uf_user";s:0:"";s:10:"tag_search";s:0:"";s:11:"uf_group_id";s:0:"";s:14:"component_mode";s:1:"7";s:8:"operator";s:3:"AND";s:25:"display_relationship_type";s:5:"1_a_b";s:15:"privacy_options";a:0:{}s:16:"privacy_operator";s:2:"OR";s:14:"privacy_toggle";s:1:"1";s:13:"email_on_hold";a:1:{s:7:"on_hold";s:0:"";}s:30:"preferred_communication_method";a:5:{i:1;s:0:"";i:2;s:0:"";i:3;s:0:"";i:4;s:0:"";i:5;s:0:"";}s:18:"preferred_language";s:0:"";s:13:"phone_numeric";s:0:"";s:22:"phone_location_type_id";s:0:"";s:19:"phone_phone_type_id";s:0:"";s:19:"hidden_relationship";s:1:"1";s:16:"relation_type_id";s:0:"";s:20:"relation_target_name";s:0:"";s:15:"relation_status";s:1:"2";s:19:"relation_permission";s:1:"0";s:21:"relation_target_group";a:0:{}s:28:"relation_start_date_relative";s:0:"";s:23:"relation_start_date_low";s:0:"";s:24:"relation_start_date_high";s:0:"";s:26:"relation_end_date_relative";s:0:"";s:21:"relation_end_date_low";s:0:"";s:22:"relation_end_date_high";s:0:"";s:4:"task";s:2:"14";s:8:"radio_ts";s:6:"ts_all";}',
    'add' => '4.5',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Smart Search template for generated groups',
    'help_text' => 'Smart Search template for generated groups',
  ),
);